

BTC:
    priceUnit:
        - USD
    decimalPlace:
        - 2
    updateFreq: 60
    discordBotKey: 
    guildId: 846280566487777291

ETH:
    priceUnit:
        - USD
    decimalPlace:
        - 2
    updateFreq: 60
    discordBotKey: 
    guildId: 846280053209825300

CONV:
    priceUnit:
        - USD
    decimalPlace:
        - 2
    updateFreq: 60
    discordBotKey: 
    guildId: 846207284119863316

# YFI:
#     priceUnit:
#         - USD
#         - ETH
#     decimalPlace:
#         - 0
#         - 2
#     updateFreq: 120
#     discordBotKey: ODQ2NDI0MjcxMzMxOTE3ODg0.YKvUCA.Q1mKYw7PwpAi-SeZoIA2CLN6KBk
#     guildId: 846424271331917884

