BTC:
    priceUnit:
        - USD
    decimalPlace:
        - 2
    updateFreq: 60
    discordBotKey: ODQ2MjgwNTY2NDg3Nzc3Mjkx.YKtOMg.QrsaFQ0OCXPJV6VaAnBLQDVWdVg
    guildId: 846280566487777291

ETH:
    priceUnit:
        - USD
    decimalPlace:
        - 2
    updateFreq: 60
    discordBotKey: ODQ2MjgwMDUzMjA5ODI1MzAw.YKtNtw.IZxcDDiQG69AkMWnv5HWrsbHMus
    guildId: 846280053209825300

CONV:
    priceUnit:
        - USD
    decimalPlace:
        - 2
    updateFreq: 60
    discordBotKey: ODQ2MjA3Mjg0MTE5ODYzMzE2.YKsJ8g.GcbtyjEEGvYC3drQMo7-Rkwfvqc
    guildId: 846207284119863316

# YFI:
#     priceUnit:
#         - USD
#         - ETH
#     decimalPlace:
#         - 0
#         - 2
#     updateFreq: 120
#     discordBotKey: ODQ2NDI0MjcxMzMxOTE3ODg0.YKvUCA.Q1mKYw7PwpAi-SeZoIA2CLN6KBk
#     guildId: 846424271331917884

